# Project information
site_name: Template Repo
site_description: 'Make documentation easy'
copyright: Darth Veitcher


# Nav
nav:
  - 'Introduction': index.md
  - 'Embed draw.io': drawio.md

# Repository
repo_name: 'darth-veitcher/mkdocs-starter'
repo_url: 'https://github.com/darth-veitcher/mkdocs-starter'

# GitHub Pages
docs_dir: docs_src
site_dir: docs
site_url: 'https://docs.jamesveitch.dev/mkdocs-starter'
use_directory_urls: false

# Use the Material theme config
# https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
  name: 'material'
  custom_dir: 'docs_src/theme'
  icon:
    logo: 'material/library'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    # text: 'Abel'  # Ubuntu
    code: 'Hackman'  # Ubuntu Mono

# Extensions
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:
  - toc:
      baselevel: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
plugins:
  - search
  - minify:
      minify_html: true